#!/usr/bin/python3
import sys


def factorize(number):
    i = 2

    if number < 2:
        return

    while number % i != 0:
        i += 1

    return i, number // i


def process_file(filename):
    try:
        with open(filename) as file:
            for line in file:
                number = int(line.strip())
                factors = factorize(number)
                if factors:
                    print("{:.0f}={:.0f}*{:.0f}".format(number, factors[1], factors[0]))
    except:
        pass


if __name__ == '__main__':
    if len(sys.argv) != 2:
        exit()

    process_file(sys.argv[1])
